@startuml
class Program {
    + {static} Main(args:string[]) : void
    {static} printHome() : void
    {static} printCommands() : void
    {static} printHelp() : void
    + {static} printCanvas(canv:List<String>) : string
    + {static} PrintStack(s:Stack<string>) : string
}
class Shape {
    + getCircle() : string
    + getRectangle() : string
    + getEllipse() : string
    + getLine() : string
    + getPolyline() : string
    + getPolygon() : string
    + getPath() : string
}
Program +-- Shape
@enduml
